const ECONOMY = require('./config');
const { statements, ensureUser, transaction } = require('./db');

function clampMoney(value) { return Math.max(0, Math.min(ECONOMY.maxMoney, Math.trunc(value))); }
function randomInt(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
function levelForXp(xp) { return Math.floor(Math.pow(xp / ECONOMY.levels.baseXp, 1 / ECONOMY.levels.growth)); }
function xpForLevel(level) { return Math.ceil(ECONOMY.levels.baseXp * Math.pow(level, ECONOMY.levels.growth)); }
function cooldown(user, action) { const row = statements.cooldown.get(user.guild_id, user.user_id, action); return Math.max(0, Number(row?.available_at || 0) - Date.now()); }
function setCooldown(user, action, ms) { require('./db').db.prepare('INSERT INTO cooldowns(guild_id,user_id,action,available_at) VALUES(?,?,?,?) ON CONFLICT(guild_id,user_id,action) DO UPDATE SET available_at=excluded.available_at').run(user.guild_id, user.user_id, action, Date.now() + ms); }
function log(user, kind, amount, targetId = null) { require('./db').db.prepare('INSERT INTO transactions(guild_id,actor_id,target_id,kind,amount,created_at) VALUES(?,?,?,?,?,?)').run(user.guild_id, user.user_id, targetId, kind, amount, Date.now()); }
function addXp(user, amount) { const nextXp = user.xp + amount; const oldLevel = user.level; const newLevel = levelForXp(nextXp); const reward = Math.max(0, newLevel - oldLevel) * ECONOMY.levels.levelReward; require('./db').db.prepare('UPDATE users SET xp=?,level=?,wallet=MIN(?,wallet+?) WHERE guild_id=? AND user_id=?').run(nextXp, newLevel, ECONOMY.maxMoney, reward, user.guild_id, user.user_id); return { level: newLevel, gained: amount, reward, advanced: newLevel > oldLevel }; }
function profile(guildId, userId) { return ensureUser(guildId, userId); }
function balance(guildId, userId) { return profile(guildId, userId); }
function action(guildId, userId, name, cooldownMs, work) { return transaction(() => { const user = ensureUser(guildId, userId); const left = cooldown(user, name); if (left) throw new Error(`COOLDOWN:${left}`); const result = work(user); setCooldown(user, name, cooldownMs); return result; }); }
function daily(guildId, userId) { return transaction(() => { const user = ensureUser(guildId, userId); const now = Date.now(); const left = Math.max(0, user.last_daily + ECONOMY.daily.cooldownMs - now); if (left) throw new Error(`COOLDOWN:${left}`); const streak = user.last_daily && now - user.last_daily <= ECONOMY.daily.cooldownMs * 2 ? user.streak + 1 : 1; const amount = ECONOMY.daily.base + Math.min(Math.max(0, streak - 1), ECONOMY.daily.maxStreakBonus / ECONOMY.daily.streakBonus) * ECONOMY.daily.streakBonus; require('./db').db.prepare('UPDATE users SET wallet=MIN(?,wallet+?),streak=?,last_daily=? WHERE guild_id=? AND user_id=?').run(ECONOMY.maxMoney, amount, streak, now, guildId, userId); const xp = addXp(user, ECONOMY.xp.daily); log(user, 'daily', amount); return { amount, streak, nextAt: now + ECONOMY.daily.cooldownMs, xp }; }); }
function work(guildId, userId) { return action(guildId, userId, 'work', ECONOMY.work.cooldownMs, user => { const amount = randomInt(ECONOMY.work.min, ECONOMY.work.max); require('./db').db.prepare('UPDATE users SET wallet=MIN(?,wallet+?) WHERE guild_id=? AND user_id=?').run(ECONOMY.maxMoney, amount, guildId, userId); log(user, 'work', amount); return { amount, xp: addXp(user, ECONOMY.xp.work) }; }); }
function crime(guildId, userId) { return action(guildId, userId, 'crime', ECONOMY.crime.cooldownMs, user => { const won = Math.random() < ECONOMY.crime.winChance; const amount = randomInt(won ? ECONOMY.crime.min : ECONOMY.crime.fineMin, won ? ECONOMY.crime.max : ECONOMY.crime.fineMax); const delta = won ? amount : -Math.min(amount, user.wallet); require('./db').db.prepare('UPDATE users SET wallet=? WHERE guild_id=? AND user_id=?').run(clampMoney(user.wallet + delta), guildId, userId); log(user, won ? 'crime_win' : 'crime_loss', delta); return { won, amount, xp: addXp(user, ECONOMY.xp.crime) }; }); }
function transfer(guildId, fromId, toId, amount) { if (!Number.isInteger(amount) || amount <= 0) throw new Error('Kwota musi być dodatnią liczbą całkowitą.'); return transaction(() => { const from = ensureUser(guildId, fromId); const to = ensureUser(guildId, toId); if (from.wallet < amount) throw new Error('Nie masz wystarczających środków w portfelu.'); require('./db').db.prepare('UPDATE users SET wallet=wallet-? WHERE guild_id=? AND user_id=? AND wallet>=?').run(amount, guildId, fromId, amount); require('./db').db.prepare('UPDATE users SET wallet=MIN(?,wallet+?) WHERE guild_id=? AND user_id=?').run(ECONOMY.maxMoney, amount, guildId, toId); log(from, 'pay', -amount, toId); return addXp(from, ECONOMY.xp.transfer); }); }
function move(guildId, userId, amount, direction) { return transaction(() => { const user = ensureUser(guildId, userId); const value = amount === 'all' ? (direction === 'deposit' ? user.wallet : user.bank) : Number(amount); if (!Number.isInteger(value) || value <= 0) throw new Error('Kwota musi być dodatnią liczbą całkowitą albo `all`.'); if (direction === 'deposit' && user.wallet < value || direction === 'withdraw' && user.bank < value) throw new Error('Niewystarczające środki.'); const wallet = direction === 'deposit' ? user.wallet - value : user.wallet + value; const bank = direction === 'deposit' ? user.bank + value : user.bank - value; require('./db').db.prepare('UPDATE users SET wallet=?,bank=? WHERE guild_id=? AND user_id=?').run(wallet, bank, guildId, userId); log(user, direction, value); return { wallet, bank, xp: addXp(user, ECONOMY.xp.command) }; }); }
function leaderboard(guildId) { return statements.leaderboard.all(guildId); }
function inventory(guildId, userId) { ensureUser(guildId, userId); return statements.allInventory.all(guildId, userId); }
function buy(guildId, userId, item) { return transaction(() => { const user = ensureUser(guildId, userId); if (user.wallet < item.price) throw new Error('Nie masz wystarczających środków.'); require('./db').db.prepare('UPDATE users SET wallet=wallet-? WHERE guild_id=? AND user_id=? AND wallet>=?').run(item.price, guildId, userId, item.price); require('./db').db.prepare('INSERT INTO inventory VALUES(?,?,?,1) ON CONFLICT(guild_id,user_id,item_id) DO UPDATE SET quantity=quantity+1').run(guildId, userId, item.id); log(user, 'buy', -item.price); return addXp(user, ECONOMY.xp.shop); }); }
function useItem(guildId, userId, item) { return transaction(() => { const user = ensureUser(guildId, userId); const owned = statements.inventory.get(guildId, userId, item.id); if (!owned?.quantity) throw new Error('Nie posiadasz tego przedmiotu.'); require('./db').db.prepare('UPDATE inventory SET quantity=quantity-1 WHERE guild_id=? AND user_id=? AND item_id=? AND quantity>0').run(guildId, userId, item.id); if (item.effect.startsWith('xp:')) { const xp = addXp(user, Number(item.effect.split(':')[1])); return { message: `Otrzymujesz ${xp.gained} XP.` }; } return { message: 'Przedmiot został użyty.' }; }); }
function rob(guildId, fromId, toId) { return action(guildId, fromId, 'rob', ECONOMY.rob.cooldownMs, from => { const target = ensureUser(guildId, toId); if (target.wallet < ECONOMY.rob.minWallet) throw new Error('Ofiara nie ma wymaganej ilości pieniędzy w portfelu.'); const won = Math.random() < ECONOMY.rob.winChance; const amount = won ? Math.max(1, Math.floor(target.wallet * (ECONOMY.rob.shareMin + Math.random() * (ECONOMY.rob.shareMax - ECONOMY.rob.shareMin)))) : Math.min(from.wallet, randomInt(ECONOMY.rob.fineMin, ECONOMY.rob.fineMax)); if (won) { require('./db').db.prepare('UPDATE users SET wallet=wallet+? WHERE guild_id=? AND user_id=?').run(amount, guildId, fromId); require('./db').db.prepare('UPDATE users SET wallet=wallet-? WHERE guild_id=? AND user_id=?').run(amount, guildId, toId); } else require('./db').db.prepare('UPDATE users SET wallet=wallet-? WHERE guild_id=? AND user_id=?').run(amount, guildId, fromId); log(from, won ? 'rob_win' : 'rob_loss', won ? amount : -amount, toId); return { won, amount, xp: addXp(from, ECONOMY.xp.rob) }; }); }
module.exports = { ECONOMY, profile, balance, daily, work, crime, transfer, move, leaderboard, inventory, buy, useItem, rob, cooldown, xpForLevel };
